src/MyGarage.Web/Models/ErrorViewModel.cs
using System;

namespace MyGarage.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/MyGarage.Web/ViewModels/Account/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MyGarage.Web.ViewModels.Account
{
    public class LoginViewModel
    {
        [Required] public string Username { get; set; }
        [Required] 
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

src/MyGarage.Web/Areas/Cars/Controllers/CarsController.cs
using Microsoft.AspNetCore.Mvc;
using MyGarage.Data;
using MyGarage.Data.Abstraction.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyGarage.Service.Abstraction;

namespace MyGarage.Web.Areas.Cars.Controllers
{    
    [Area("Cars")]
    public class CarsController : Controller
    {
        public async Task <IActionResult> Index()
        {
            IEnumerable<Car> Cars = await _carsService.GetAll();
            return View(Cars);
        }
        private readonly ICarsService _carsService;
        
        public CarsController(ICarsService service)
        {
            _carsService = service;
        }

        
        
        // CAR CREATION \\
        
        public IActionResult Create()
        {
            return View();
        }        
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Brand,Model,CreationYear,NbSeats,Power,Price")] Car car)
        {
            if (ModelState.IsValid)
            {
                await _carsService.Add(car);
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }
        
        // Car Edition  \\
        
       
        
        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _carsService.GetById((int)id);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Brand,Model,CreationYear,NbSeats,Power,Price")] Car car)
        {
            if (id != car.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
              
                  await  _carsService.Update(id, car);
                    
                
                return RedirectToAction("Index");
            }
            return View(car);
        }
        
        
        
    }
    
    
}

src/MyGarage.Web/Controllers/AccountController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyGarage.Data.Abstraction.Models;
using MyGarage.Web.ViewModels.Account;

namespace MyGarage.Web.Controllers
{
    public class AccountController : Controller
    {


        private SignInManager<ApplicationUser> _signInManager;

        public AccountController(SignInManager<ApplicationUser> manager)
        {
            _signInManager = manager;
        }
        
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login([Bind("Username,Password")] LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.Username, model.Password, false, false);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Invalid Login");
                    return View(model);
                }
            }

            return View(model);
        }

        public IActionResult AccessDenied()
        {
            return View();

        }
        
    }
}

src/MyGarage.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyGarage.Web.Models;

namespace MyGarage.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/MyGarage.Web/ViewComponents/CarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using MyGarage.Data;
using MyGarage.Data.Abstraction.Models;

namespace MyGarage.Web.ViewComponents
{
    public class CarViewComponent : ViewComponent
    {
        private readonly GarageContext  _context;
        
        public CarViewComponent(GarageContext context)
        {
            _context = context;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = _context.Cars.ToList();
            return await Task.FromResult((IViewComponentResult) View("Index", model));
            
        }
        
    }
}

src/MyGarage.Web/Areas/Cars/Views/cars/Create.cshtml
@using MyGarage.Data.Abstraction.Models
@model MyGarage.Data.Abstraction.Models.Car
@{
    Layout = "_Layout";
    ViewData["Title"] = "Create";
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="danger"></div>
<div class="form-group">
    <label asp-for="Brand" class="control-label"></label>
    <input asp-for="Brand" class="form-control"/>
    <span asp-validation-for="Brand" class="danger"></span>
    
    <label asp-for="Model" class="control-label"></label>
    <input asp-for="Model" class="form-control"/>
    <span asp-validation-for="Model" class="danger"></span>
  
    <label asp-for="Power" class="control-label"></label>
    <input asp-for="Power" class="form-control"/>
    <span asp-validation-for="Power" class="danger"></span>  
    
    <label asp-for="Price" class="control-label"></label>
    <input asp-for="Price" class="form-control"/>
    <span asp-validation-for="Price" class="danger"></span>
    
    <label asp-for="NbSeats" class="control-label"></label>
    <input asp-for="NbSeats" class="form-control"/>
    <span asp-validation-for="NbSeats" class="danger"></span>
    
    <label asp-for="CreationYear" class="control-label"></label>
    <input asp-for="CreationYear" class="form-control"/>
    <span asp-validation-for="CreationYear" class="danger"></span>
    
    @* <a asp-action="Details" asp-route-id="@Car.ID">Details</a> | *@
    @* <a asp-action="Delete" asp-route-id="@Car.ID">Delete</a> *@
    
    <input type="submit" value="Create" class="btn btn-default"/>
</div>      
</form>

    </div>        
</div>

src/MyGarage.Web/Areas/Cars/Views/cars/Edit.cshtml
@using MyGarage.Data.Abstraction.Models
@model MyGarage.Data.Abstraction.Models.Car
@{
    Layout = "_Layout";

    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Car</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="ID" />
        <div class="form-group">
            <label asp-for="Brand" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CreationYear" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CreationYear" class="form-control" />
                <span asp-validation-for="CreationYear" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Model" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Power" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Power" class="form-control" />
                <span asp-validation-for="Power" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Price" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="NbSeats" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="NbSeats" class="form-control" />
                <span asp-validation-for="NbSeats" class="text-danger"></span>
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/MyGarage.Web/Areas/Cars/Views/cars/Index.cshtml
@model IEnumerable<MyGarage.Data.Abstraction.Models.Car>
@{
    Layout = "_Layout";
}
<h2>All Cars</h2>
<a asp-area="Cars" asp-controller="Cars" asp-action="Create" class="btn btn-primary">Create Car</a>
<table class="table">
    <thead></thead>
    <th>
        @Html.DisplayNameFor(model => model.Brand)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.Model)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.CreationYear)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.NbSeats)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.Power)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.Price)
    </th>
    <th>
        edit 
    </th>
    <tbody>
    @foreach (var item in Model)
    {
        @await Html.PartialAsync("_CarDetails",item)
    }
    </tbody>
</table>
<h2>Cars View Component</h2>
    @(await Component.InvokeAsync("Car"))


@section Scripts
{
    <environment include="Development">
        <script type="text/javascript" src="~/js/DeleteCar.js"></script>
    </environment>
    <environment exclude="development">
        <script type="text/javascript" src="~/js/DeleteCar.min.js"></script>
    </environment>
}

src/MyGarage.Web/Areas/Cars/Views/cars/_CarDetails.cshtml
@model MyGarage.Data.Abstraction.Models.Car
<tr>
    <td>
        @Html.DisplayFor(model => model.Brand)
    </td>
    <td>
        @Html.DisplayFor(model => model.Model)
    </td>
    <td>
        @Html.DisplayFor(model => model.CreationYear)
    </td>
    <td>
        @Html.DisplayFor(model => model.NbSeats)
    </td>
    <td>
        @Html.DisplayFor(model => model.Power)
    </td>
    <td>
        @Html.DisplayFor(model => model.Price)
    </td>
    <td>
        <a asp-action="Edit" asp-route-id="@Model.ID" class="btn btn-primary">Edit</a> |
        <button class="delete-car btn btn-danger" data-car-id="@Model.ID">Delete</button>
    </td>
</tr>

src/MyGarage.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/MyGarage.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/MyGarage.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

src/MyGarage.Web/Views/Shared/Components/Car/Index.cshtml
@model IList<MyGarage.Data.Abstraction.Models.Car>
<table class="table">
    <thead></thead>
    <tbody>
@foreach (var item in Model)
{
    <tr>

    <td>@item.Brand</td>
    <td>@item.Model</td>
    <td>@item.Power</td>
    <td>@item.Price</td>
    <td>@item.CreationYear</td>
    <td>@item.NbSeats</td>
                     </tr>

}
    </tbody>

</table>

src/MyGarage.Web/Views/Shared/_Layout.cshtml
﻿<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyGarage.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MyGarage.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="Cars" asp-controller="Cars" asp-action="Index">Cars</a></li>
                    <li><a asp-area="" asp-controller="Account" asp-action="Login">Login</a></li>   
                </ul>
            </div>
        </div>
        </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - MyGarage.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>